spring:
  application:
    name: CryptoGuardians

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 공용 DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.196.130.9:3306/crython?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 20240814

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/crypton?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # GCS(Google Cloud Storage)
  cloud:
    gcp:
      storage:
        credentials:
          location: my-project-1558663198607-36efb3acc2c6.json

gcs:
  bucket:
    name: crython-file-storage